-- Initialisation formation_loaded (schema crebas.sql + donnees de demo, ids >= 1000)

INSERT INTO SEXE (SEX_CD, LABEL) VALUES ('M', 'Masculin');
INSERT INTO SEXE (SEX_CD, LABEL) VALUES ('F', 'Feminin');

INSERT INTO COUNTRY (COU_ID, NAME) VALUES (1128, 'France');
INSERT INTO COUNTRY (COU_ID, NAME) VALUES (840, 'Etats-Unis');
INSERT INTO COUNTRY (COU_ID, NAME) VALUES (826, 'Royaume-Uni');
INSERT INTO COUNTRY (COU_ID, NAME) VALUES (250, 'Allemagne');
INSERT INTO COUNTRY (COU_ID, NAME) VALUES (392, 'Japon');

INSERT INTO USER_GROUP (GRP_ID, NAME) VALUES (1, 'Administrateur');
INSERT INTO USER_GROUP (GRP_ID, NAME) VALUES (2, 'Utilisateur');

INSERT INTO USER (USR_ID, LOGIN, NAME, EMAIL, COU_ID, GRP_ID) VALUES (1000, 'admin', 'Administrateur', 'admin@vertigo.io', 1128, 1);
INSERT INTO USER (USR_ID, LOGIN, NAME, EMAIL, COU_ID, GRP_ID) VALUES (1001, 'user', 'Utilisateur', 'user@vertigo.io', 840, 2);

INSERT INTO ACTOR (ACT_ID, NAME, SEXE) VALUES (1000, 'Tom Hanks', 'M');
INSERT INTO ACTOR (ACT_ID, NAME, SEXE) VALUES (1001, 'Robin Williams', 'M');
INSERT INTO ACTOR (ACT_ID, NAME, SEXE) VALUES (1002, 'Meryl Streep', 'F');
INSERT INTO ACTOR (ACT_ID, NAME, SEXE) VALUES (1003, 'Harrison Ford', 'M');
INSERT INTO ACTOR (ACT_ID, NAME, SEXE) VALUES (1004, 'Cate Blanchett', 'F');
INSERT INTO ACTOR (ACT_ID, NAME, SEXE) VALUES (1005, 'Brad Pitt', 'M');

INSERT INTO MOVIE (MOV_ID, NAME, YEAR, IMDBID, COU_ID) VALUES (1000, 'Forrest Gump', 1994, 'tt0109830', 840);
INSERT INTO MOVIE (MOV_ID, NAME, YEAR, IMDBID, COU_ID) VALUES (1001, 'Good Will Hunting', 1997, 'tt0119217', 840);
INSERT INTO MOVIE (MOV_ID, NAME, YEAR, IMDBID, COU_ID) VALUES (1002, 'The Iron Giant', 1999, 'tt0120630', 840);
INSERT INTO MOVIE (MOV_ID, NAME, YEAR, IMDBID, COU_ID) VALUES (1003, 'The Aviator', 2004, 'tt0338751', 840);
INSERT INTO MOVIE (MOV_ID, NAME, YEAR, IMDBID, COU_ID) VALUES (1004, 'The Grand Budapest Hotel', 2014, 'tt0338751', 250);
INSERT INTO MOVIE (MOV_ID, NAME, YEAR, IMDBID, COU_ID) VALUES (1005, 'The Blue Lagoon', 1980, 'tt0080699', 826);

INSERT INTO ROLE (ROL_ID, AS_CHARACTER, MOV_ID, ACT_ID) VALUES (1000, '<1>Forrest Gump', 1000, 1000);
INSERT INTO ROLE (ROL_ID, AS_CHARACTER, MOV_ID, ACT_ID) VALUES (1001, '<2>Jenny Curran', 1000, 1002);
INSERT INTO ROLE (ROL_ID, AS_CHARACTER, MOV_ID, ACT_ID) VALUES (1002, '<1>Will Hunting', 1001, 1000);
INSERT INTO ROLE (ROL_ID, AS_CHARACTER, MOV_ID, ACT_ID) VALUES (1003, '<2>Sean Maguire', 1001, 1001);
INSERT INTO ROLE (ROL_ID, AS_CHARACTER, MOV_ID, ACT_ID) VALUES (1004, '<1>Young Hogarth', 1002, 1001);
INSERT INTO ROLE (ROL_ID, AS_CHARACTER, MOV_ID, ACT_ID) VALUES (1005, '<1>Hugh Hefner', 1003, 1000);
INSERT INTO ROLE (ROL_ID, AS_CHARACTER, MOV_ID, ACT_ID) VALUES (1006, '<1>Ephraim', 1004, 1003);
INSERT INTO ROLE (ROL_ID, AS_CHARACTER, MOV_ID, ACT_ID) VALUES (1007, '<2>M.', 1004, 1004);
INSERT INTO ROLE (ROL_ID, AS_CHARACTER, MOV_ID, ACT_ID) VALUES (1008, '<1>Richard', 1005, 1005);
