package io.mars.domain.base;

import io.vertigo.dynamo.domain.model.Entity;
import io.vertigo.dynamo.domain.model.URI;
import io.vertigo.dynamo.domain.stereotype.Field;
import io.vertigo.dynamo.domain.util.DtObjectUtil;
import io.vertigo.lang.Generated;

/**
 * This class is automatically generated.
 * DO NOT EDIT THIS FILE DIRECTLY.
 */
@Generated
public final class MaintenanceOp implements Entity {
	private static final long serialVersionUID = 1L;

	private Long moId;
	private String ticketCode;
	private String name;
	private String description;
	private java.util.Date dueDate;

	/** {@inheritDoc} */
	@Override
	public URI<MaintenanceOp> getURI() {
		return URI.of(this);
	}
	
	/**
	 * Champ : ID.
	 * Récupère la valeur de la propriété 'Id'.
	 * @return Long moId <b>Obligatoire</b>
	 */
	@Field(domain = "DO_ID", type = "ID", required = true, label = "Id")
	public Long getMoId() {
		return moId;
	}

	/**
	 * Champ : ID.
	 * Définit la valeur de la propriété 'Id'.
	 * @param moId Long <b>Obligatoire</b>
	 */
	public void setMoId(final Long moId) {
		this.moId = moId;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Ticket Number'.
	 * @return String ticketCode
	 */
	@Field(domain = "DO_LABEL", label = "Ticket Number")
	public String getTicketCode() {
		return ticketCode;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Ticket Number'.
	 * @param ticketCode String
	 */
	public void setTicketCode(final String ticketCode) {
		this.ticketCode = ticketCode;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Mainenance Operation'.
	 * @return String name
	 */
	@Field(domain = "DO_LABEL", label = "Mainenance Operation")
	public String getName() {
		return name;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Mainenance Operation'.
	 * @param name String
	 */
	public void setName(final String name) {
		this.name = name;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Maintenance Operation Descrption'.
	 * @return String description
	 */
	@Field(domain = "DO_DESCRIPTION", label = "Maintenance Operation Descrption")
	public String getDescription() {
		return description;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Maintenance Operation Descrption'.
	 * @param description String
	 */
	public void setDescription(final String description) {
		this.description = description;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Due Date'.
	 * @return Date dueDate
	 */
	@Field(domain = "DO_DATE", label = "Due Date")
	public java.util.Date getDueDate() {
		return dueDate;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Due Date'.
	 * @param dueDate Date
	 */
	public void setDueDate(final java.util.Date dueDate) {
		this.dueDate = dueDate;
	}
	
	/** {@inheritDoc} */
	@Override
	public String toString() {
		return DtObjectUtil.toString(this);
	}
}
