package io.mars.basemanagement;

import javax.inject.Inject;

import io.vertigo.app.Home;
import io.vertigo.dynamo.task.TaskManager;
import io.vertigo.dynamo.task.metamodel.TaskDefinition;
import io.vertigo.dynamo.task.model.Task;
import io.vertigo.dynamo.task.model.TaskBuilder;
import io.vertigo.dynamo.store.StoreServices;
import io.vertigo.lang.Assertion;
import io.vertigo.lang.Generated;

/**
 * This class is automatically generated.
 * DO NOT EDIT THIS FILE DIRECTLY.
 */
 @Generated
public final class BasemanagementPAO implements StoreServices {
	private final TaskManager taskManager;

	/**
	 * Constructeur.
	 * @param taskManager Manager des Task
	 */
	@Inject
	public BasemanagementPAO(final TaskManager taskManager) {
		Assertion.checkNotNull(taskManager);
		//-----
		this.taskManager = taskManager;
	}

	/**
	 * Creates a taskBuilder.
	 * @param name  the name of the task
	 * @return the builder 
	 */
	private static TaskBuilder createTaskBuilder(final String name) {
		final TaskDefinition taskDefinition = Home.getApp().getDefinitionSpace().resolve(name, TaskDefinition.class);
		return Task.builder(taskDefinition);
	}

	/**
	 * Execute la tache TK_GET_BASES_SUMMARY.
	 * @return io.mars.basemanagement.domain.BasesSummary basesSummary
	*/
	public io.mars.basemanagement.domain.BasesSummary getBasesSummary() {
		final Task task = createTaskBuilder("TK_GET_BASES_SUMMARY")
				.build();
		return getTaskManager()
				.execute(task)
				.getResult();
	}

	/**
	 * Execute la tache TK_GET_BASE_OVERVIEW.
	 * @param baseId Long 
	 * @return io.mars.basemanagement.domain.BaseOverview baseOverview
	*/
	public io.mars.basemanagement.domain.BaseOverview getBaseOverview(final Long baseId) {
		final Task task = createTaskBuilder("TK_GET_BASE_OVERVIEW")
				.addValue("BASE_ID", baseId)
				.build();
		return getTaskManager()
				.execute(task)
				.getResult();
	}

	/**
	 * Execute la tache TK_GET_EQUIPMENTS_OVERVIEW.
	 * @param baseId Long 
	 * @return io.vertigo.dynamo.domain.model.DtList<io.mars.basemanagement.domain.EquipmentOverview> overview
	*/
	public io.vertigo.dynamo.domain.model.DtList<io.mars.basemanagement.domain.EquipmentOverview> getEquipmentsOverview(final Long baseId) {
		final Task task = createTaskBuilder("TK_GET_EQUIPMENTS_OVERVIEW")
				.addValue("BASE_ID", baseId)
				.build();
		return getTaskManager()
				.execute(task)
				.getResult();
	}

	/**
	 * Execute la tache TK_GET_EQUIPMENT_MAINTENANCE_OVERVIEW.
	 * @param equipmentId Long 
	 * @return io.mars.basemanagement.domain.EquipmentMaintenanceOverview equipmentMaintenanceOverview
	*/
	public io.mars.basemanagement.domain.EquipmentMaintenanceOverview getEquipmentMaintenanceOverview(final Long equipmentId) {
		final Task task = createTaskBuilder("TK_GET_EQUIPMENT_MAINTENANCE_OVERVIEW")
				.addValue("EQUIPMENT_ID", equipmentId)
				.build();
		return getTaskManager()
				.execute(task)
				.getResult();
	}

	/**
	 * Execute la tache TK_LOAD_BASE_INDEX.
	 * @param baseIds java.util.List<Long> 
	 * @return io.vertigo.dynamo.domain.model.DtList<io.mars.basemanagement.search.BaseIndex> dtcIndex
	*/
	public io.vertigo.dynamo.domain.model.DtList<io.mars.basemanagement.search.BaseIndex> loadBaseIndex(final java.util.List<Long> baseIds) {
		final Task task = createTaskBuilder("TK_LOAD_BASE_INDEX")
				.addValue("BASE_IDS", baseIds)
				.build();
		return getTaskManager()
				.execute(task)
				.getResult();
	}

	/**
	 * Execute la tache TK_LOAD_EQUIPMENT_INDEX.
	 * @param equipmentIds java.util.List<Long> 
	 * @return io.vertigo.dynamo.domain.model.DtList<io.mars.basemanagement.search.EquipmentIndex> dtcIndex
	*/
	public io.vertigo.dynamo.domain.model.DtList<io.mars.basemanagement.search.EquipmentIndex> loadEquipmentIndex(final java.util.List<Long> equipmentIds) {
		final Task task = createTaskBuilder("TK_LOAD_EQUIPMENT_INDEX")
				.addValue("EQUIPMENT_IDS", equipmentIds)
				.build();
		return getTaskManager()
				.execute(task)
				.getResult();
	}

	/**
	 * Execute la tache TK_SELECT_BASE_ID.
	 * @return java.util.List<Long> baseIdList
	*/
	public java.util.List<Long> selectBaseId() {
		final Task task = createTaskBuilder("TK_SELECT_BASE_ID")
				.build();
		return getTaskManager()
				.execute(task)
				.getResult();
	}

	/**
	 * Execute la tache TK_SELECT_BUSINESS_ID.
	 * @return java.util.List<Long> businessIdList
	*/
	public java.util.List<Long> selectBusinessId() {
		final Task task = createTaskBuilder("TK_SELECT_BUSINESS_ID")
				.build();
		return getTaskManager()
				.execute(task)
				.getResult();
	}

	/**
	 * Execute la tache TK_SELECT_GEOSECTOR_ID.
	 * @return java.util.List<Long> geosectorIdList
	*/
	public java.util.List<Long> selectGeosectorId() {
		final Task task = createTaskBuilder("TK_SELECT_GEOSECTOR_ID")
				.build();
		return getTaskManager()
				.execute(task)
				.getResult();
	}

	private TaskManager getTaskManager() {
		return taskManager;
	}
}
