package io.mars.basemanagement.domain;

import io.vertigo.dynamo.domain.model.DtStaticMasterData;
import io.vertigo.dynamo.domain.model.UID;
import io.vertigo.dynamo.domain.stereotype.Field;
import io.vertigo.dynamo.domain.util.DtObjectUtil;
import io.vertigo.lang.Generated;

/**
 * This class is automatically generated.
 * DO NOT EDIT THIS FILE DIRECTLY.
 */
@Generated
public final class BaseType implements DtStaticMasterData {
	private static final long serialVersionUID = 1L;

	private String baseTypeId;
	private String label;

	/** {@inheritDoc} */
	@Override
	public UID<BaseType> getUID() {
		return UID.of(this);
	}
	
	/**
	 * Champ : ID.
	 * Récupère la valeur de la propriété 'Id'.
	 * @return String baseTypeId <b>Obligatoire</b>
	 */
	@Field(domain = "DoCode", type = "ID", required = true, label = "Id")
	public String getBaseTypeId() {
		return baseTypeId;
	}

	/**
	 * Champ : ID.
	 * Définit la valeur de la propriété 'Id'.
	 * @param baseTypeId String <b>Obligatoire</b>
	 */
	public void setBaseTypeId(final String baseTypeId) {
		this.baseTypeId = baseTypeId;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Base Type Label'.
	 * @return String label
	 */
	@Field(domain = "DoLabel", label = "Base Type Label")
	public String getLabel() {
		return label;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Base Type Label'.
	 * @param label String
	 */
	public void setLabel(final String label) {
		this.label = label;
	}
	
	/** {@inheritDoc} */
	@Override
	public String toString() {
		return DtObjectUtil.toString(this);
	}
}
