package io.mars.basemanagement.domain;

import io.vertigo.dynamo.domain.model.DtObject;
import io.vertigo.dynamo.domain.stereotype.Field;
import io.vertigo.dynamo.domain.util.DtObjectUtil;
import io.vertigo.lang.Generated;

/**
 * This class is automatically generated.
 * DO NOT EDIT THIS FILE DIRECTLY.
 */
@Generated
public final class EquipmentOverview implements DtObject {
	private static final long serialVersionUID = 1L;

	private Long businessId;
	private Long count;
	private String businessName;
	private String businessIcon;
	private Long okCount;
	private Long downCount;
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Business Id'.
	 * @return Long businessId
	 */
	@Field(domain = "DoId", label = "Business Id")
	public Long getBusinessId() {
		return businessId;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Business Id'.
	 * @param businessId Long
	 */
	public void setBusinessId(final Long businessId) {
		this.businessId = businessId;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Count by business'.
	 * @return Long count
	 */
	@Field(domain = "DoCount", label = "Count by business")
	public Long getCount() {
		return count;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Count by business'.
	 * @param count Long
	 */
	public void setCount(final Long count) {
		this.count = count;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Business'.
	 * @return String businessName
	 */
	@Field(domain = "DoLabel", label = "Business")
	public String getBusinessName() {
		return businessName;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Business'.
	 * @param businessName String
	 */
	public void setBusinessName(final String businessName) {
		this.businessName = businessName;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Business'.
	 * @return String businessIcon
	 */
	@Field(domain = "DoLabel", label = "Business")
	public String getBusinessIcon() {
		return businessIcon;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Business'.
	 * @param businessIcon String
	 */
	public void setBusinessIcon(final String businessIcon) {
		this.businessIcon = businessIcon;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Ok count'.
	 * @return Long okCount
	 */
	@Field(domain = "DoCount", label = "Ok count")
	public Long getOkCount() {
		return okCount;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Ok count'.
	 * @param okCount Long
	 */
	public void setOkCount(final Long okCount) {
		this.okCount = okCount;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Down count'.
	 * @return Long downCount
	 */
	@Field(domain = "DoCount", label = "Down count")
	public Long getDownCount() {
		return downCount;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Down count'.
	 * @param downCount Long
	 */
	public void setDownCount(final Long downCount) {
		this.downCount = downCount;
	}
	
	/** {@inheritDoc} */
	@Override
	public String toString() {
		return DtObjectUtil.toString(this);
	}
}
