package io.mars.hr.domain;

import io.vertigo.dynamo.domain.model.DtObject;
import io.vertigo.dynamo.domain.stereotype.Field;
import io.vertigo.dynamo.domain.util.DtObjectUtil;
import io.vertigo.lang.Generated;

/**
 * This class is automatically generated.
 * DO NOT EDIT THIS FILE DIRECTLY.
 */
@Generated
public final class MissionDisplay implements DtObject {
	private static final long serialVersionUID = 1L;

	private Long missionId;
	private String role;
	private String baseName;
	private String businessName;
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Id'.
	 * @return Long missionId
	 */
	@Field(domain = "DoId", label = "Id")
	public Long getMissionId() {
		return missionId;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Id'.
	 * @param missionId Long
	 */
	public void setMissionId(final Long missionId) {
		this.missionId = missionId;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Role'.
	 * @return String role
	 */
	@Field(domain = "DoCode", label = "Role")
	public String getRole() {
		return role;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Role'.
	 * @param role String
	 */
	public void setRole(final String role) {
		this.role = role;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Base'.
	 * @return String baseName
	 */
	@Field(domain = "DoLabel", label = "Base")
	public String getBaseName() {
		return baseName;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Base'.
	 * @param baseName String
	 */
	public void setBaseName(final String baseName) {
		this.baseName = baseName;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Business'.
	 * @return String businessName
	 */
	@Field(domain = "DoLabel", label = "Business")
	public String getBusinessName() {
		return businessName;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Business'.
	 * @param businessName String
	 */
	public void setBusinessName(final String businessName) {
		this.businessName = businessName;
	}
	
	/** {@inheritDoc} */
	@Override
	public String toString() {
		return DtObjectUtil.toString(this);
	}
}
