package io.vertigo.demo.domain.client;

import io.vertigo.dynamo.domain.model.DtObject;
import io.vertigo.dynamo.domain.model.VAccessor;
import io.vertigo.dynamo.domain.stereotype.Field;
import io.vertigo.dynamo.domain.util.DtObjectUtil;
import io.vertigo.lang.Generated;

/**
 * This class is automatically generated.
 * DO NOT EDIT THIS FILE DIRECTLY.
 */
 @Generated
public final class AdresseSelection implements DtObject {
	private static final long serialVersionUID = 1L;

	private final VAccessor<io.vertigo.demo.domain.referentiel.Region> regIdAccessor = new VAccessor<>(io.vertigo.demo.domain.referentiel.Region.class, "region");
	private final VAccessor<io.vertigo.demo.domain.referentiel.Departement> depIdAccessor = new VAccessor<>(io.vertigo.demo.domain.referentiel.Departement.class, "departement");
	private final VAccessor<io.vertigo.demo.domain.referentiel.CodePostal> cpoIdAccessor = new VAccessor<>(io.vertigo.demo.domain.referentiel.CodePostal.class, "codePostal");

	/**
	 * Champ : FOREIGN_KEY.
	 * Récupère la valeur de la propriété 'Region'.
	 * @return Long regId
	 */
	@Field(domain = "DO_IDENTIFIANT", type = "FOREIGN_KEY", label = "Region")
	public Long getRegId() {
		return (Long)  regIdAccessor.getId();
	}

	/**
	 * Champ : FOREIGN_KEY.
	 * Définit la valeur de la propriété 'Region'.
	 * @param regId Long
	 */
	public void setRegId(final Long regId) {
		regIdAccessor.setId(regId);
	}

	/**
	 * Champ : FOREIGN_KEY.
	 * Récupère la valeur de la propriété 'D�partement'.
	 * @return Long depId
	 */
	@Field(domain = "DO_IDENTIFIANT", type = "FOREIGN_KEY", label = "D�partement")
	public Long getDepId() {
		return (Long)  depIdAccessor.getId();
	}

	/**
	 * Champ : FOREIGN_KEY.
	 * Définit la valeur de la propriété 'D�partement'.
	 * @param depId Long
	 */
	public void setDepId(final Long depId) {
		depIdAccessor.setId(depId);
	}

	/**
	 * Champ : FOREIGN_KEY.
	 * Récupère la valeur de la propriété 'Code postal'.
	 * @return Long cpoId
	 */
	@Field(domain = "DO_IDENTIFIANT", type = "FOREIGN_KEY", label = "Code postal")
	public Long getCpoId() {
		return (Long)  cpoIdAccessor.getId();
	}

	/**
	 * Champ : FOREIGN_KEY.
	 * Définit la valeur de la propriété 'Code postal'.
	 * @param cpoId Long
	 */
	public void setCpoId(final Long cpoId) {
		cpoIdAccessor.setId(cpoId);
	}

	/**
	 * Association : Code postal.
	 * @return io.vertigo.demo.domain.referentiel.CodePostal
	 */
	public io.vertigo.demo.domain.referentiel.CodePostal getCodePostal() {
		return cpoIdAccessor.get();
	}

	/**
	 * Retourne l'URI: Code postal.
	 * @return URI de l'association
	 */
	@io.vertigo.dynamo.domain.stereotype.Association(
			name = "A_CPO_ADR",
			fkFieldName = "CPO_ID",
			primaryDtDefinitionName = "DT_CODE_POSTAL",
			primaryIsNavigable = true,
			primaryRole = "CodePostal",
			primaryLabel = "Code postal",
			primaryMultiplicity = "0..1",
			foreignDtDefinitionName = "DT_ADRESSE_SELECTION",
			foreignIsNavigable = false,
			foreignRole = "CodePostal",
			foreignLabel = "Code postal",
			foreignMultiplicity = "0..*")
	public io.vertigo.dynamo.domain.model.URI<io.vertigo.demo.domain.referentiel.CodePostal> getCodePostalURI() {
		return cpoIdAccessor.getURI();
	}

	/**
	 * Association : D�partement.
	 * @return io.vertigo.demo.domain.referentiel.Departement
	 */
	public io.vertigo.demo.domain.referentiel.Departement getDepartement() {
		return depIdAccessor.get();
	}

	/**
	 * Retourne l'URI: D�partement.
	 * @return URI de l'association
	 */
	@io.vertigo.dynamo.domain.stereotype.Association(
			name = "A_DEP_ADR",
			fkFieldName = "DEP_ID",
			primaryDtDefinitionName = "DT_DEPARTEMENT",
			primaryIsNavigable = true,
			primaryRole = "Departement",
			primaryLabel = "D�partement",
			primaryMultiplicity = "0..1",
			foreignDtDefinitionName = "DT_ADRESSE_SELECTION",
			foreignIsNavigable = false,
			foreignRole = "Departement",
			foreignLabel = "D�partement",
			foreignMultiplicity = "0..*")
	public io.vertigo.dynamo.domain.model.URI<io.vertigo.demo.domain.referentiel.Departement> getDepartementURI() {
		return depIdAccessor.getURI();
	}

	/**
	 * Association : Region.
	 * @return io.vertigo.demo.domain.referentiel.Region
	 */
	public io.vertigo.demo.domain.referentiel.Region getRegion() {
		return regIdAccessor.get();
	}

	/**
	 * Retourne l'URI: Region.
	 * @return URI de l'association
	 */
	@io.vertigo.dynamo.domain.stereotype.Association(
			name = "A_REG_ADR",
			fkFieldName = "REG_ID",
			primaryDtDefinitionName = "DT_REGION",
			primaryIsNavigable = true,
			primaryRole = "Region",
			primaryLabel = "Region",
			primaryMultiplicity = "0..1",
			foreignDtDefinitionName = "DT_ADRESSE_SELECTION",
			foreignIsNavigable = false,
			foreignRole = "Region",
			foreignLabel = "Region",
			foreignMultiplicity = "0..*")
	public io.vertigo.dynamo.domain.model.URI<io.vertigo.demo.domain.referentiel.Region> getRegionURI() {
		return regIdAccessor.getURI();
	}


	/** {@inheritDoc} */
	@Override
	public String toString() {
		return DtObjectUtil.toString(this);
	}
}
