package io.vertigo.samples.dao.domain;

import io.vertigo.dynamo.domain.model.DtObject;
import io.vertigo.dynamo.domain.stereotype.Field;
import io.vertigo.dynamo.domain.util.DtObjectUtil;
import io.vertigo.lang.Generated;

/**
 * This class is automatically generated.
 * DO NOT EDIT THIS FILE DIRECTLY.
 */
@Generated
public final class MovieByYear implements DtObject {
	private static final long serialVersionUID = 1L;

	private Integer year;
	private Long moviesCount;
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Année'.
	 * @return Integer year
	 */
	@Field(domain = "DoYear", label = "Année")
	public Integer getYear() {
		return year;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Année'.
	 * @param year Integer
	 */
	public void setYear(final Integer year) {
		this.year = year;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Nombre de film'.
	 * @return Long moviesCount
	 */
	@Field(domain = "DoId", label = "Nombre de film")
	public Long getMoviesCount() {
		return moviesCount;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Nombre de film'.
	 * @param moviesCount Long
	 */
	public void setMoviesCount(final Long moviesCount) {
		this.moviesCount = moviesCount;
	}
	
	/** {@inheritDoc} */
	@Override
	public String toString() {
		return DtObjectUtil.toString(this);
	}
}
